version: "3"

services:
  web:
    build: .
    tty: true
    volumes:
      - ./:/workspace
      - /home/vscode/.cache/ms-playwright
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sirashou55@yahoo.co.jp
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin4_data:
